name: Build and publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    name: Build wheels for all supported Python versions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (for pip/cibuildwheel)
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        run: python -m cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: "pp* cp27* cp36*"

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
